name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: systemic-engineering/ci/.github/workflows/rust-nix-publish.yml@main
    with:
      crate-name: imperfect
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
